# Generated by Django 3.2 on 2021-04-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant',
            new_name='user',
        ),
    ]
