# Generated by Django 3.2 on 2021-04-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_rename_merchant_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='merchant',
        ),
    ]
