# Generated by Django 3.2 on 2021-04-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_rename_user_order_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
