# Generated by Django 3.2 on 2021-04-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0004_alter_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
