# Generated by Django 3.2 on 2021-04-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_alter_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
