# Generated by Django 3.2 on 2021-04-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_order_order_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
